FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# Phoenix

This is a preliminary sketch of the Onboarding API

## Home [/]

### Get Home Resource [GET]

+ Response 200 (text/html)
            
        <h1>Home</h1>
        
        <h1>ITEM:1q2w3e4r5t</h1>
        
        <p><a href="/list">LIST</a></p>
        <p>data fields display here...</p>
        <p><a href="/1q2w3e4r5t/company">Show Company Info Form</a></p>
        <p><a href="/1q2w3e4r5t/account">Show Account Info Form</a></p>
        <p><a href="/1q2w3e4r5t/activity">Show Activity Info Form</a></p>
        <p><a href="/1q2w3e4r5t/approve">Show Approve Form</a></p>
        <p><a href="/1q2w3e4r5t/reject">Show Reject Form</a></p>