FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# Phoenix

This is a preliminary sketch of the Onboarding API

## Home [/]

### Get Home Resource [GET]

+ Response 200 (text/html)
            
        <h1>Home</h1>