/*
 * Phoenix Payroll API
 *
 * design and build great web apis
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Contract : IEquatable<Contract>
    { 
        /// <summary>
        /// Gets or Sets ContractIdentifier
        /// </summary>
        [DataMember(Name="contractIdentifier")]
        public decimal? ContractIdentifier { get; set; }

        /// <summary>
        /// Gets or Sets HandleCode
        /// </summary>
        [DataMember(Name="handle-code")]
        public string HandleCode { get; set; }

        /// <summary>
        /// Gets or Sets TypeCode
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum TypeCodeEnum
        {
            /// <summary>
            /// Enum _1Enum for 1
            /// </summary>
            [EnumMember(Value = "1")]
            _1Enum = 0,
            /// <summary>
            /// Enum _100Enum for 10.0
            /// </summary>
            [EnumMember(Value = "10.0")]
            _100Enum = 1,
            /// <summary>
            /// Enum _500Enum for 50.0
            /// </summary>
            [EnumMember(Value = "50.0")]
            _500Enum = 2        }

        /// <summary>
        /// Gets or Sets TypeCode
        /// </summary>
        [DataMember(Name="type-code")]
        public TypeCodeEnum? TypeCode { get; set; }

        /// <summary>
        /// Gets or Sets DateStarted
        /// </summary>
        [DataMember(Name="date-started")]
        public string DateStarted { get; set; }

        /// <summary>
        /// Gets or Sets DateClosed
        /// </summary>
        [DataMember(Name="date-closed")]
        public string DateClosed { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Contract {\n");
            sb.Append("  ContractIdentifier: ").Append(ContractIdentifier).Append("\n");
            sb.Append("  HandleCode: ").Append(HandleCode).Append("\n");
            sb.Append("  TypeCode: ").Append(TypeCode).Append("\n");
            sb.Append("  DateStarted: ").Append(DateStarted).Append("\n");
            sb.Append("  DateClosed: ").Append(DateClosed).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Contract)obj);
        }

        /// <summary>
        /// Returns true if Contract instances are equal
        /// </summary>
        /// <param name="other">Instance of Contract to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Contract other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ContractIdentifier == other.ContractIdentifier ||
                    ContractIdentifier != null &&
                    ContractIdentifier.Equals(other.ContractIdentifier)
                ) && 
                (
                    HandleCode == other.HandleCode ||
                    HandleCode != null &&
                    HandleCode.Equals(other.HandleCode)
                ) && 
                (
                    TypeCode == other.TypeCode ||
                    TypeCode != null &&
                    TypeCode.Equals(other.TypeCode)
                ) && 
                (
                    DateStarted == other.DateStarted ||
                    DateStarted != null &&
                    DateStarted.Equals(other.DateStarted)
                ) && 
                (
                    DateClosed == other.DateClosed ||
                    DateClosed != null &&
                    DateClosed.Equals(other.DateClosed)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ContractIdentifier != null)
                    hashCode = hashCode * 59 + ContractIdentifier.GetHashCode();
                    if (HandleCode != null)
                    hashCode = hashCode * 59 + HandleCode.GetHashCode();
                    if (TypeCode != null)
                    hashCode = hashCode * 59 + TypeCode.GetHashCode();
                    if (DateStarted != null)
                    hashCode = hashCode * 59 + DateStarted.GetHashCode();
                    if (DateClosed != null)
                    hashCode = hashCode * 59 + DateClosed.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Contract left, Contract right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Contract left, Contract right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
